#CircleCI config schema is versioned. 
version: 2.1

# orbs are config packages to include.
orbs:
  gradle: circleci/gradle@1.0.11
  slack: circleci/slack@3.3.0

workflows:
  build_and_test:
    jobs:
      - do-it-all
      - cats
      - fanout:
          requires:
            - cats
      - assemble:
          requires:
            - fanout

jobs:
  cats:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name '*.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - circle-gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - circle-gradle-
      - run:
          name: Install
          command: |
            mkdir -p ./build/reports/profile
            GRADLE="./gradlew -PenablePublishing=true --max-workers=1 --profile"
            export GRADLE_OPTS="-Xmx1g -Xms1g"
            $GRADLE :cats:buildNeeded 
            $GRADLE :clouddriver-core:buildNeeded 
            $GRADLE :clouddriver-security:buildNeeded 
      
      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          key: circle-gradle-cats-{{ .Branch }}
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      - store_test_results:
          path: ./circleci/project-timing.xml
      #- slack/notify

  fanout:
    machine: true
    resource_class: large
    parallelism: 6
    steps:
      - checkout
      - run: |
          whoami
          pwd
      - restore_cache:
          keys: 
            - circle-gradle-cats-{{ .Branch }}
            - circle-gradle-cats
      - run:
          name: Install
          command: |
            mkdir -p ./build/reports/profile
            GRADLE="./gradlew -PenablePublishing=true --max-workers=1 --profile"
            export GRADLE_OPTS="-Xmx1g -Xms1g"
            #generate list
            THIS_NODES=$(./gradlew projects | grep '^+--' | sed 's/+--- Project\ '"'"':\([a-z_-]*\)'"'"'/\1/' | circleci tests split --split-by=timings --timings-type=classname)
            for DIR in $THIS_NODES;do
              echo "Building $DIR"
              $GRADLE :${DIR}:build
            done
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: .
            # Must be relative path from root
          paths:
            - '*'
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: '/home/circleci/.gradle'
            # Must be relative path from root
          paths:
            - 'cache'
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile




  assemble:
    machine: true
    resource_class: large
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name '*.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - circle-gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - circle-gradle-
      - restore_cache:
          keys: 
            - circle-gradle-cats-{{ .Branch }}
            - circle-gradle-cats
      - attach_workspace:
          at: .

      - attach_workspace:
          at: /home/circleci/.gradle

      - run:
          name: Build
          command: |

            GRADLE="./gradlew -PenablePublishing=true --no-daemon --max-workers=1 --profile --configure-on-demand"
            export GRADLE_OPTS="-Xmx1g -Xms1g"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Build Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              $GRADLE build javadoc
            else
              echo -e 'WARN: Only building on CircleCI'
              $GRADLE build
            fi

      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: circle-gradle-{{ checksum "/tmp/gradle_cache_seed" }}
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      #- slack/notify


  do-it-all:
    machine: true
    resource_class: large
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys: 
            - circle-gradle-full{{ .Branch }}
            - circle-gradle
      - run:
          name: Build
          command: |

            GRADLE="./gradlew -PenablePublishing=true --no-daemon --max-workers=1 --profile --configure-on-demand"
            export GRADLE_OPTS="-Xmx1g -Xms1g"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Build Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              $GRADLE build javadoc
            else
              echo -e 'WARN: Only building on CircleCI'
              $GRADLE build
            fi

      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: circle-gradle-full{{ .Branch }}
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      #- slack/notify

