#CircleCI config schema is versioned. 
version: 2.1

# orbs are config packages to include.
orbs:
  gradle: circleci/gradle@1.0.11
  slack: circleci/slack@3.3.0

workflows:
  build_and_test:
    jobs:
      - cats
      - fanout:
          requires:
            - cats
      - assemble:
          requires:
            - fanout

jobs:
  cats:
    docker:
      - image: cimg/openjdk:8u222-b10-stable
    resource_class: xlarge
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name '*.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - gradle-
      - run:
          name: Install
          command: |
            mkdir -p ./build/reports/profile
            GRADLE="./gradlew -PenablePublishing=true --max-workers=1 --profile"
            export GRADLE_OPTS="-Xmx1g -Xms1g"
            $GRADLE :cats:build
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: .
            # Must be relative path from root
          paths:
            - 'cats/build' 
            - .gradle/caches 
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      #- slack/notify

  fanout:
    docker:
      - image: cimg/openjdk:8u222-b10-stable
    resource_class: xlarge
    parallelism: 6
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name '*.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - gradle-
      - attach_workspace:
          at: .
      - run:
          name: Install
          command: |
            mkdir -p ./build/reports/profile
            GRADLE="./gradlew -PenablePublishing=true --max-workers=1 --profile"
            export GRADLE_OPTS="-Xmx1g -Xms1g"
            #generate list
            THIS_NODES=$(./gradlew projects | grep '^+--' | grep -v cats | sed 's/+--- Project\ '"'"':\([a-z_-]*\)'"'"'/\1/' | circleci tests split)
            for DIR in $THIS_NODES;do
              echo "Building $DIR"
              $GRADLE :${DIR}:build
            done
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: .
            # Must be relative path from root
          paths:
            - '**/build' 
            - .gradle/caches 
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      #- slack/notify



  assemble:
    docker:
      - image: cimg/openjdk:8u222-b10-stable
    resource_class: xlarge
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name '*.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - gradle-
      - attach_workspace:
          at: .

      - run:
          name: Build
          command: |

            GRADLE="./gradlew -PenablePublishing=true --no-daemon --max-workers=1 --profile --configure-on-demand"
            export GRADLE_OPTS="-Xmx1g -Xms1g"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Build Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              $GRADLE build javadoc
            else
              echo -e 'WARN: Only building on CircleCI'
              $GRADLE build
            fi

      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}
      - store_artifacts:
          when: always
          path: ./build/reports/profile
          destination: profile
      #- slack/notify


